<?xml version="1.0"?>
<robot name="dorothy" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="body.xacro" />
    <xacro:include filename="pod.xacro" />
    <xacro:include filename="wheel.xacro" />
  <xacro:property name="body_h" value="0.03" />
  <xacro:property name="pod_h" value="0.1" />
    <link name="base_link">
    </link>
    <joint name="body_joint" type="fixed">
        <parent link="base_link" />
        <child link="body_link" />
    </joint>

    <joint name="pod_joint" type="fixed">
        <parent link="body_link" />
        <child link="pod" />
        <origin xyz="0 0 ${(pod_h+body_h)/2}" rpy="0 0 3.14" />
    </joint>
    <link name="base_footprint">
    </link>
    <joint name="footprint_joint" type="fixed">
        <child link="base_link" />
        <parent link="base_footprint" />
    </joint>

    <xacro:make_wheel prefix="left_front" reflect="1" xyz="${wheels_lf} ${wheels_w} 0" steerable="1" toe="0" wheel_base_link="body_link" />
    <xacro:make_wheel prefix="right_front" reflect="-1" xyz="${wheels_lf} ${-wheels_w} 0" steerable="1" toe="0" wheel_base_link="body_link"/>
    <xacro:make_wheel prefix="left_back" reflect="1" xyz="${-wheels_lb} ${wheels_w} 0" steerable="0" toe="${2.5*M_PI/180}" wheel_base_link="body_link"/>
    <xacro:make_wheel prefix="right_back" reflect="-1" xyz="${-wheels_lb} ${-wheels_w} 0" steerable="0" toe="${2.5*M_PI/180}" wheel_base_link="body_link"/>

    <gazebo>
        <!-- <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"></plugin> -->
        <!-- <plugin name="JointStatePublisher" filename="libJointStatePublisher.so" /> -->
        <plugin name="ArduCopter_Plugin" filename="libArduPilotPlugin.so">
            <fdm_addr>127.0.0.1</fdm_addr>
            <fdm_port_in>9002</fdm_port_in>
            <fdm_port_out>9003</fdm_port_out>
            <modelXYZToAirplaneXForwardZDown>0 0 0 ${M_PI} 0 0</modelXYZToAirplaneXForwardZDown>
            <gazeboXYZToNED>0 0 0 ${M_PI} 0 0</gazeboXYZToNED>
            <imuName>imu_sensor</imuName>
            <connectionTimeoutMaxCount>5</connectionTimeoutMaxCount>
            
            <xacro:macro name="wheel_drive" params="joint">
                <control channel="2">
                    <type>VELOCITY</type>
                    <offset>-0.5</offset>
                    <p_gain>10</p_gain>
                    <!-- <cmd_max>1000</cmd_max>
                    <cmd_min>-1000</cmd_min> -->
                    <jointName>${joint}_hub_to_wheel</jointName>
                    <multiplier>150</multiplier>
                </control>
            </xacro:macro>
            <xacro:wheel_drive joint="left_back" />
            <xacro:wheel_drive joint="left_front" />
            <xacro:wheel_drive joint="right_back" />
            <xacro:wheel_drive joint="right_front" />

            <xacro:macro name="steer_drive" params="joint">
                <control channel="0">
                    <type>POSITION</type>
                    <offset>-0.5</offset>
                    <p_gain>30</p_gain>
                    <cmd_max>100</cmd_max>
                    <cmd_min>-100</cmd_min>
                    <jointName>${joint}_strut_to_strut_dummy</jointName>
                    <multiplier>${M_PI/2}</multiplier>
                </control>
            </xacro:macro>
            <xacro:steer_drive joint="left_front" />
            <xacro:steer_drive joint="right_front" />
        </plugin>


    </gazebo>
</robot> 