<?xml version="1.0"?>
<robot name="one_wheel"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="ackermann_wheels.xacro" />
    <xacro:include filename="lib.xacro" />

    <xacro:property name="l_b" value="0.5"/>
    <xacro:property name="w_b" value="0.3"/>
    <xacro:property name="h_b" value="0.1"/>
    <xacro:property name="m_b" value="8"/>


    <xacro:property name="wheel_h" value="0.1"/>
    <xacro:property name="wheel_spacing" value="0.1"/>
    <link name="body_link">
        <visual>
            <geometry>
                <box size="${l_b} ${w_b} ${h_b}" />
            </geometry>
            <material name="Body_Gray" />
        </visual>
        <collision>
            <geometry>
                <box size="${l_b} ${w_b} ${h_b}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="${m_b}" x="${l_b}" y="${w_b}" z="${h_b}" />
    </link>
    <gazebo reference="body_link">
        <material value="Gazebo/Wood" />
    </gazebo>

    <link name="base_link">

    </link>

    <joint name="body_joint" type="fixed">
        <parent link="base_link" />
        <child link="body_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
    <xacro:autocar_front_wheel name="fr" steer_name="r_steer" rpy="0 0 0" xyz="-0.3 ${wheel_spacing+(w_b/2)} ${-wheel_h}" base_link_name="body_link"/>
    <xacro:autocar_front_wheel name="fl" steer_name="l_steer" rpy="0 0 0" xyz="-0.3 ${-(wheel_spacing+(w_b/2))}  ${-wheel_h}" base_link_name="body_link"/>
    <xacro:autocar_back_wheel name="br" rpy="0 0 0" xyz="0.3 ${wheel_spacing+(w_b/2)} ${-wheel_h}" base_link_name="body_link"/>
    <xacro:autocar_back_wheel name="bl" rpy="0 0 0" xyz="0.3 ${-(wheel_spacing+(w_b/2))} ${-wheel_h}" base_link_name="body_link"/>

    <xacro:property name="m_steer_wheel" value="0.8"/>
    <xacro:property name="r_steer_wheel" value="0.01"/>
    <xacro:property name="h_steer_wheel" value="0.01"/>
    <link name="steering_wheel">

        <xacro:cylinder_inertia m="${m_steer_wheel}" r="${r_steer_wheel}" h="${h_steer_wheel}"/>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${r_steer_wheel}" length="${h_steer_wheel}" />
            </geometry>
            <material name="Wheel_Black"/>
        </visual>
    </link>

    <joint name="steering_joint" type="continuous">
        <origin rpy="0 0 0" xyz="0 0 ${(h_b+h_steer_wheel)/2+0.001}"/>
        <parent link="body_link"/>
        <child link="steering_wheel"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit effort="100.0" lower="-6" upper="6" velocity="100"/>
        <dynamics damping="0.0" friction="1.0"/>
    </joint>

    <xacro:property name="steering_pid" value="100 0 17"/>
    <!-- <xacro:property name="steering_pid" value="0 0 0"/> -->
    <xacro:property name="steering_i_range" value="0 0"/>
   
    <xacro:property name="linear_pid" value="1 0 0"/>
    <xacro:property name="linear_i_range" value="0 0"/>

    <gazebo>
        <plugin name='ackermann_drive' filename='libgazebo_ros_ackermann_drive.so'>

            <ros>
                <namespace>ackermann_dorothy</namespace>
                <remapping>cmd_vel:=cmd_vel</remapping>
                <remapping>odom:=odom</remapping>
                <remapping>distance:=distance</remapping>
            </ros>

            <update_rate>100.0</update_rate>

            <!-- wheels -->
            <front_left_joint>fl_axle</front_left_joint>
            <front_right_joint>fr_axle</front_right_joint>
            <rear_left_joint>bl_axle</rear_left_joint>
            <rear_right_joint>br_axle</rear_right_joint>
            <left_steering_joint>l_steer</left_steering_joint>
            <right_steering_joint>r_steer</right_steering_joint>
            <!-- <steering_wheel_joint>steering_joint</steering_wheel_joint> -->


            <!-- Max absolute steer angle for tyre in radians-->
            <!-- Any cmd_vel angular z greater than this would be capped -->
            <max_steer>0.6</max_steer>

            <!-- Max absolute steering angle of steering wheel -->
            <!-- Max absolute steering angle of steering wheel -->
            <max_steering_angle>2</max_steering_angle>

            <!-- Max absolute linear speed in m/s -->
            <max_speed>10</max_speed>

            <!-- PID tuning -->
            <left_steering_pid_gain>${steering_pid} </left_steering_pid_gain>
            <left_steering_i_range>${steering_i_range}</left_steering_i_range>
            <right_steering_pid_gain>${steering_pid}</right_steering_pid_gain>
            <right_steering_i_range>${steering_i_range}</right_steering_i_range>
            <linear_velocity_pid_gain>${linear_pid}</linear_velocity_pid_gain>
            <linear_velocity_i_range>${linear_i_range}</linear_velocity_i_range>

            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <publish_distance>true</publish_distance>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>

        </plugin>
    </gazebo>

</robot>
