<?xml version="1.0"?>


<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.14159" />
  <xacro:property name="lidar_height_from_pod" value="0.15" />
  <xacro:property name="pod_x" value="0.4"/>
  <xacro:property name="pod_y" value="0.2"/>
  <xacro:property name="pod_z" value="0.1"/>
  <xacro:include filename="lib.xacro" />
  <material name="blue">
    <color rgba="0 0 .7 1" />
  </material>
  <material name="red">
    <color rgba="0.7 0 0 1" />
  </material>

  <link name="pod">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0" />
      <geometry>
        <box size="${pod_x} ${pod_y} ${pod_z}" />
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <geometry>
        <box size="${pod_x} ${pod_y} ${pod_z}" />
      </geometry>
    </collision>

    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <!--_LIDAR -->
  <link name="laser">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0" />
      <geometry>
        <cylinder length="0.0315" radius="0.055" />
      </geometry>
      <material name="red"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0" />
      <geometry>
        <cylinder length="0.0315" radius="0.055" />
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <gazebo reference="laser">
    <material>Gazebo/FlatBlack</material>
    <sensor type="ray" name="lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>15</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>0.0</min_angle>
            <max_angle>6.28319</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120</min>
          <max>10.0</max>
          <resolution>0.050</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser</frame_name>
      </plugin>
    </sensor>
  </gazebo>
  <joint name="scan_joint" type="fixed">
    <parent link="pod" />
    <child link="laser" />
    <origin xyz="0 0 ${lidar_height_from_pod}" rpy="0 0 3.14" />
  </joint>
  <gazebo reference="scan_joint">
    <preserveFixedJoint>true</preserveFixedJoint>
    <!-- <disableFixedJointLumping>true</disableFixedJointLumping> -->
  </gazebo>

  <!-- IMU -->
  <link name="imu">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0" />
      <geometry>
        <box  size="0.03 0.03 0.03" />
      </geometry>
      <material name="red"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box length="0.03" width="0.03" height="0.03" />
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>
  <gazebo reference="imu">
    <material>Gazebo/FlatBlack</material>

    <sensor name="my_imu" type="imu">
      <always_on>true</always_on>
      <!-- Publish at 30 hz -->
      <update_rate>30</update_rate>
      <plugin name="my_imu_plugin" filename="libgazebo_ros_imu_sensor.so">
        <ros>
          <!-- Will publish to /imu/data -->
          <namespace>/imu</namespace>
          <remapping>~/out:=data</remapping>
        </ros>
        <!-- frame_name ommited, will be "my_link" -->
      </plugin>
    </sensor>
  </gazebo>
  <joint name="imu_joint" type="fixed">
    <parent link="pod" />
    <child link="imu" />
    <origin xyz="${(pod_x-0.03)/2} 0 ${(pod_z+0.03)/2}" rpy="0 0 3.14" />
  </joint>
  <gazebo reference="imu_joint">
    <preserveFixedJoint>true</preserveFixedJoint>
    <!-- <disableFixedJointLumping>true</disableFixedJointLumping> -->
  </gazebo>

  <xacro:cam suffix="front" xyz="0.3 0.0 0.0" rpy="0 0 ${0}" pod_link_name="pod"/>
  <xacro:cam suffix="right" xyz="-0.1 -0.12 0.05" rpy="0 0 ${-M_PI/5}" pod_link_name="pod"/>
  <xacro:cam suffix="left" xyz="-0.1 0.12 0.05" rpy="0 0 ${M_PI/5}" pod_link_name="pod"/>
  <xacro:cam suffix="rear" xyz="-0.3 0.0 0.0" rpy="0 0 ${M_PI}" pod_link_name="pod"/>

</robot>